services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-55334}:5432"

  openci-controller:
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
