name: runner
description: OpenCI's CLI
version: 1.0.3
environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  dart_firebase_admin: ^0.3.0
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  dartssh2: ^2.8.2
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.1
  github: ^9.24.0
  google_play_api_kit: ^0.2.6
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.5
  openci_models: ^1.0.3
  process_run: ^0.13.3
  pub_updater: ^0.3.0
  sentry: ^7.18.0
  signals_core: ^5.2.2
  supabase: ^2.2.5
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0

executables:
  runner:
