name: openci_runner
description: OpenCI Worker
version: 0.10.3
repository: https://github.com/open-ci-io/openci/tree/develop/apps/openci_runner
homepage: https://open-ci.io
environment:
  sdk: ^3.8.1
dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  dart_firebase_admin: ^0.4.1
  dart_jsonwebtoken: ^3.2.0
  dartssh2: ^2.12.0
  github: ^9.25.0
  http: ^1.4.0
  logger: ^2.5.0
  mason_logger: ^0.3.3
  openci_models: ^1.3.3
  process_run: ^1.2.4
  pub_updater: ^0.5.0
  sentry: ^8.14.2
  signals_core: ^6.0.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.0
  build_verify: ^3.1.1
  build_version: ^2.1.1
  mockito: ^5.4.6
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^7.0.0

executables:
  ? openci_runner
