name: openci_models
description: OpenCI Models
version: 1.0.8
repository: https://github.com/open-ci-io/openci/tree/develop/packages/openci_models

environment:
  sdk: ^3.3.4

dependencies:
  dart_firebase_admin: ^0.3.1
  freezed: ^2.4.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
