name: Check Firebase Functions Deploy

on:
  pull_request:
    branches: [main, develop]

jobs:
  firebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openci-runner/firebase/functions

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install github-apps dependencies
        working-directory: openci-runner/github-apps
        run: npm ci

      - name: Build github-apps
        working-directory: openci-runner/github-apps
        run: npm run build

      - name: Install firebase-functions dependencies
        run: npm ci

      - name: Build firebase-functions
        run: npm run build

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SA_KEY }}

      - name: Deploy
        run: npx firebase-tools emulators:exec --only functions "echo"
