name: Firebase Functions Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "openci-runner/firebase/functions/**"
      - ".github/workflows/firebase-functions-ci-cd.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "openci-runner/firebase/functions/**"
      - ".github/workflows/firebase-functions-ci-cd.yml"

jobs:
  github-apps-tests:
    uses: ./.github/workflows/reusable-github-apps-tests.yml

  firebase-functions-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: openci-runner/firebase/functions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies for github-apps
        working-directory: openci-runner/github-apps
        run: npm ci && npm run build

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy-firebase-functions:
    needs: [github-apps-tests, firebase-functions-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: openci-runner/firebase
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SA_KEY }}

      - uses: google-github-actions/get-secretmanager-secrets@v1
        id: secrets
        with:
          secrets: |
            FB_SERVICE_ACCOUNT:projects/${{ secrets.FIREBASE_PROJECT_ID }}/secrets/FB_SERVICE_ACCOUNT/versions/latest
            GITHUB_PRIVATE_KEY:projects/${{ secrets.FIREBASE_PROJECT_ID }}/secrets/GITHUB_PRIVATE_KEY/versions/latest
            GITHUB_WEBHOOK_SECRET:projects/${{ secrets.FIREBASE_PROJECT_ID }}/secrets/GITHUB_WEBHOOK_SECRET/versions/latest

      - name: Create an dotenv file
        working-directory: openci-runner/firebase/functions
        run: |
          touch .env
          echo GITHUB_APP_ID = ${{secrets.GH_APP_ID}} >> .env
          echo "cat .env"

      - name: Install github-apps dependencies
        working-directory: openci-runner/github-apps
        run: npm ci

      - name: Build github-apps
        working-directory: openci-runner/github-apps
        run: npm run build

      - name: Install firebase-functions dependencies
        working-directory: openci-runner/firebase/functions
        run: npm ci

      - name: Build firebase-functions
        working-directory: openci-runner/firebase/functions
        run: npm run build

      - name: Deploy Functions
        run: npx firebase-tools deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
