name: GitHub Apps Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "openci-runner/github-apps/**"
      - ".github/workflows/github-apps-tests.yml"
      - ".github/workflows/github-apps-tests-runner.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "openci-runner/github-apps/**"
      - ".github/workflows/github-apps-tests.yml"
      - ".github/workflows/github-apps-tests-runner.yml"

jobs:
  call-tests:
    uses: ./.github/workflows/github-apps-tests.yml
